# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Todd Grabowsky
logo:				 toddaboo.png
tagline:             ''
description:         ''
url:                 http://toddaboo.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Todd Grabowsky
  twitter:           toddaboo
  facebook:			 toddgrabowsky
  linkedin:			 toddgrabowsky
  email:             todd.grabowsky@gmail.com
  github:			 toddaboo

# Custom vars
version:             1.0.0
