# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               todd.grabowsky
logo:				 toddaboo.png
tagline:             ''
description:         ''
url:                 http://toddaboo.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Todd Grabowsky
  url:               https://twitter.com/toddaboo
  email:             todd.grabowsky@gmail.com

# Custom vars
version:             1.0.0
